apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: coches/frontend
        imagePullPolicy: Never
        ports:
        # - containerPort: 80
          - containerPort: 4200
        envFrom:
          - configMapRef:
              name: frontend-config
          - secretRef:
              name:  frontend-secret
            
